[2022-07-04 18:03:47,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.middle_task manual__2022-07-04T18:03:44.144396+00:00 [queued]>
[2022-07-04 18:03:47,298] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.middle_task manual__2022-07-04T18:03:44.144396+00:00 [queued]>
[2022-07-04 18:03:47,298] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 18:03:47,298] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-04 18:03:47,298] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 18:03:47,313] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): middle_task> on 2022-07-04 18:03:44.144396+00:00
[2022-07-04 18:03:47,315] {standard_task_runner.py:52} INFO - Started process 6880 to run task
[2022-07-04 18:03:47,317] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_python_operator', 'middle_task', 'manual__2022-07-04T18:03:44.144396+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/my_python_operator_dag.py', '--cfg-path', '/tmp/tmpkw_8iq8w', '--error-file', '/tmp/tmpxtsdx2tj']
[2022-07-04 18:03:47,318] {standard_task_runner.py:80} INFO - Job 409: Subtask middle_task
[2022-07-04 18:03:47,355] {task_command.py:370} INFO - Running <TaskInstance: my_python_operator.middle_task manual__2022-07-04T18:03:44.144396+00:00 [running]> on host a84f4c234c47
[2022-07-04 18:03:47,410] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=giang
AIRFLOW_CTX_DAG_ID=my_python_operator
AIRFLOW_CTX_TASK_ID=middle_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T18:03:44.144396+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T18:03:44.144396+00:00
[2022-07-04 18:03:47,410] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: middle_task() missing 1 required positional argument: 'taskInstance'
[2022-07-04 18:03:47,415] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_operator, task_id=middle_task, execution_date=20220704T180344, start_date=20220704T180347, end_date=20220704T180347
[2022-07-04 18:03:47,424] {standard_task_runner.py:97} ERROR - Failed to execute job 409 for task middle_task (middle_task() missing 1 required positional argument: 'taskInstance'; 6880)
[2022-07-04 18:03:47,448] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-04 18:03:47,472] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
