[2022-07-04 18:17:07,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.push_xcoms manual__2022-07-04T18:17:03.589379+00:00 [queued]>
[2022-07-04 18:17:07,284] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.push_xcoms manual__2022-07-04T18:17:03.589379+00:00 [queued]>
[2022-07-04 18:17:07,284] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 18:17:07,284] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-04 18:17:07,285] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 18:17:07,302] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): push_xcoms> on 2022-07-04 18:17:03.589379+00:00
[2022-07-04 18:17:07,305] {standard_task_runner.py:52} INFO - Started process 7895 to run task
[2022-07-04 18:17:07,308] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_python_operator', 'push_xcoms', 'manual__2022-07-04T18:17:03.589379+00:00', '--job-id', '423', '--raw', '--subdir', 'DAGS_FOLDER/my_python_operator_dag.py', '--cfg-path', '/tmp/tmp4mm_3iw0', '--error-file', '/tmp/tmp_itmaj3u']
[2022-07-04 18:17:07,309] {standard_task_runner.py:80} INFO - Job 423: Subtask push_xcoms
[2022-07-04 18:17:07,354] {task_command.py:370} INFO - Running <TaskInstance: my_python_operator.push_xcoms manual__2022-07-04T18:17:03.589379+00:00 [running]> on host a84f4c234c47
[2022-07-04 18:17:07,418] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=giang
AIRFLOW_CTX_DAG_ID=my_python_operator
AIRFLOW_CTX_TASK_ID=push_xcoms
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T18:17:03.589379+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T18:17:03.589379+00:00
[2022-07-04 18:17:07,418] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_python_operator_dag.py", line 22, in push_xcoms
    ti.xcom.push(key='first_name',value='nguyen')
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2022-07-04 18:17:07,424] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_operator, task_id=push_xcoms, execution_date=20220704T181703, start_date=20220704T181707, end_date=20220704T181707
[2022-07-04 18:17:07,433] {standard_task_runner.py:97} ERROR - Failed to execute job 423 for task push_xcoms ('TaskInstance' object has no attribute 'xcom'; 7895)
[2022-07-04 18:17:07,439] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-04 18:17:07,462] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
