[2022-07-04 18:25:59,187] {processor.py:153} INFO - Started process (PID=8522) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:25:59,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:25:59,188] {logging_mixin.py:115} INFO - [2022-07-04 18:25:59,188] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:25:59,212] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:25:59,224] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.040 seconds
[2022-07-04 18:26:15,276] {processor.py:153} INFO - Started process (PID=8541) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:15,277] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:26:15,277] {logging_mixin.py:115} INFO - [2022-07-04 18:26:15,277] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:15,285] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:15,295] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.021 seconds
[2022-07-04 18:26:38,430] {processor.py:153} INFO - Started process (PID=8574) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:38,431] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:26:38,431] {logging_mixin.py:115} INFO - [2022-07-04 18:26:38,431] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:38,439] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:26:38,447] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.018 seconds
[2022-07-04 18:27:08,596] {processor.py:153} INFO - Started process (PID=8616) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:08,596] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:27:08,597] {logging_mixin.py:115} INFO - [2022-07-04 18:27:08,597] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:08,605] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:08,613] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.018 seconds
[2022-07-04 18:27:17,621] {processor.py:153} INFO - Started process (PID=8630) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:17,621] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:27:17,621] {logging_mixin.py:115} INFO - [2022-07-04 18:27:17,621] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:17,629] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:17,639] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.019 seconds
[2022-07-04 18:27:35,768] {processor.py:153} INFO - Started process (PID=8654) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:35,768] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:27:35,769] {logging_mixin.py:115} INFO - [2022-07-04 18:27:35,769] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:35,779] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:27:35,791] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.027 seconds
[2022-07-04 18:28:05,853] {processor.py:153} INFO - Started process (PID=8696) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:05,853] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:28:05,854] {logging_mixin.py:115} INFO - [2022-07-04 18:28:05,854] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:05,862] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:05,871] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.019 seconds
[2022-07-04 18:28:20,906] {processor.py:153} INFO - Started process (PID=8710) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:20,919] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:28:20,920] {logging_mixin.py:115} INFO - [2022-07-04 18:28:20,920] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:20,943] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:20,953] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.056 seconds
[2022-07-04 18:28:28,981] {processor.py:153} INFO - Started process (PID=8729) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:28,981] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:28:28,982] {logging_mixin.py:115} INFO - [2022-07-04 18:28:28,982] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:28,991] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:29,001] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.022 seconds
[2022-07-04 18:28:30,986] {processor.py:153} INFO - Started process (PID=8734) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:30,995] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:28:30,995] {logging_mixin.py:115} INFO - [2022-07-04 18:28:30,995] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:31,003] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:28:31,014] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.030 seconds
[2022-07-04 18:29:01,149] {processor.py:153} INFO - Started process (PID=8776) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:01,150] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:29:01,150] {logging_mixin.py:115} INFO - [2022-07-04 18:29:01,150] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:01,158] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:01,167] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.020 seconds
[2022-07-04 18:29:30,343] {processor.py:153} INFO - Started process (PID=8818) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:30,354] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:29:30,356] {logging_mixin.py:115} INFO - [2022-07-04 18:29:30,356] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:30,387] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:30,401] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.066 seconds
[2022-07-04 18:29:32,439] {processor.py:153} INFO - Started process (PID=8823) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:32,440] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:29:32,441] {logging_mixin.py:115} INFO - [2022-07-04 18:29:32,441] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:32,455] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:29:32,467] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.034 seconds
[2022-07-04 18:30:02,560] {processor.py:153} INFO - Started process (PID=8865) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:02,560] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:30:02,561] {logging_mixin.py:115} INFO - [2022-07-04 18:30:02,561] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:02,568] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:02,577] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.018 seconds
[2022-07-04 18:30:11,610] {processor.py:153} INFO - Started process (PID=8875) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:11,621] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:30:11,621] {logging_mixin.py:115} INFO - [2022-07-04 18:30:11,621] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:11,631] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:11,641] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.033 seconds
[2022-07-04 18:30:41,747] {processor.py:153} INFO - Started process (PID=8917) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:41,759] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:30:41,760] {logging_mixin.py:115} INFO - [2022-07-04 18:30:41,760] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:41,786] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:41,800] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.061 seconds
[2022-07-04 18:30:43,786] {processor.py:153} INFO - Started process (PID=8922) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:43,787] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:30:43,788] {logging_mixin.py:115} INFO - [2022-07-04 18:30:43,788] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:43,812] {logging_mixin.py:115} INFO - [2022-07-04 18:30:43,812] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 4, in <module>
    from dags.my_python_operator_dag import greet
ModuleNotFoundError: No module named 'dags'
[2022-07-04 18:30:43,813] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:30:43,833] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.055 seconds
[2022-07-04 18:31:13,965] {processor.py:153} INFO - Started process (PID=8964) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:13,977] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:31:13,978] {logging_mixin.py:115} INFO - [2022-07-04 18:31:13,978] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:14,010] {logging_mixin.py:115} INFO - [2022-07-04 18:31:14,010] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 4, in <module>
    from dags.my_python_operator_dag import greet
ModuleNotFoundError: No module named 'dags'
[2022-07-04 18:31:14,011] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:14,029] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.071 seconds
[2022-07-04 18:31:44,153] {processor.py:153} INFO - Started process (PID=9006) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:44,164] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:31:44,165] {logging_mixin.py:115} INFO - [2022-07-04 18:31:44,165] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:44,179] {logging_mixin.py:115} INFO - [2022-07-04 18:31:44,179] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 4, in <module>
    from dags.my_python_operator_dag import greet
ModuleNotFoundError: No module named 'dags'
[2022-07-04 18:31:44,179] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:44,195] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.045 seconds
[2022-07-04 18:31:45,205] {processor.py:153} INFO - Started process (PID=9011) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:45,205] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:31:45,205] {logging_mixin.py:115} INFO - [2022-07-04 18:31:45,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:45,220] {logging_mixin.py:115} INFO - [2022-07-04 18:31:45,220] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 4, in <module>
    from dags.my_python_operator_dag import task
ModuleNotFoundError: No module named 'dags'
[2022-07-04 18:31:45,220] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:45,234] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.031 seconds
[2022-07-04 18:31:57,238] {processor.py:153} INFO - Started process (PID=9025) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:57,239] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:31:57,239] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,239] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:57,251] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:31:57,300] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,300] {manager.py:508} INFO - Created Permission View: can delete on DAG:dag_with_taskflow_api
[2022-07-04 18:31:57,307] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,307] {manager.py:508} INFO - Created Permission View: can read on DAG:dag_with_taskflow_api
[2022-07-04 18:31:57,314] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,314] {manager.py:508} INFO - Created Permission View: can edit on DAG:dag_with_taskflow_api
[2022-07-04 18:31:57,314] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,314] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:31:57,320] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,320] {dag.py:2398} INFO - Creating ORM DAG for dag_with_taskflow_api
[2022-07-04 18:31:57,329] {logging_mixin.py:115} INFO - [2022-07-04 18:31:57,329] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-01T00:00:00+00:00, run_after=2022-07-02T00:00:00+00:00
[2022-07-04 18:31:57,342] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.106 seconds
[2022-07-04 18:32:27,404] {processor.py:153} INFO - Started process (PID=9085) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:27,415] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:32:27,415] {logging_mixin.py:115} INFO - [2022-07-04 18:32:27,415] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:27,431] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:27,482] {logging_mixin.py:115} INFO - [2022-07-04 18:32:27,482] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:32:27,500] {logging_mixin.py:115} INFO - [2022-07-04 18:32:27,500] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:32:27,509] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.107 seconds
[2022-07-04 18:32:57,573] {processor.py:153} INFO - Started process (PID=9118) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:57,585] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:32:57,587] {logging_mixin.py:115} INFO - [2022-07-04 18:32:57,587] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:57,623] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:32:57,641] {logging_mixin.py:115} INFO - [2022-07-04 18:32:57,641] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:32:57,654] {logging_mixin.py:115} INFO - [2022-07-04 18:32:57,654] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:32:57,662] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.099 seconds
[2022-07-04 18:33:27,736] {processor.py:153} INFO - Started process (PID=9160) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:27,747] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:33:27,747] {logging_mixin.py:115} INFO - [2022-07-04 18:33:27,747] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:27,760] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:27,799] {logging_mixin.py:115} INFO - [2022-07-04 18:33:27,799] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:33:27,815] {logging_mixin.py:115} INFO - [2022-07-04 18:33:27,815] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:33:27,826] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.099 seconds
[2022-07-04 18:33:57,877] {processor.py:153} INFO - Started process (PID=9202) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:57,889] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:33:57,891] {logging_mixin.py:115} INFO - [2022-07-04 18:33:57,890] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:57,924] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:33:57,967] {logging_mixin.py:115} INFO - [2022-07-04 18:33:57,967] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:33:57,980] {logging_mixin.py:115} INFO - [2022-07-04 18:33:57,980] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:33:57,996] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.128 seconds
[2022-07-04 18:34:28,085] {processor.py:153} INFO - Started process (PID=9244) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:28,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:34:28,086] {logging_mixin.py:115} INFO - [2022-07-04 18:34:28,086] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:28,097] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:28,111] {logging_mixin.py:115} INFO - [2022-07-04 18:34:28,111] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:34:28,125] {logging_mixin.py:115} INFO - [2022-07-04 18:34:28,125] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:34:28,134] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.051 seconds
[2022-07-04 18:34:58,218] {processor.py:153} INFO - Started process (PID=9277) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:58,229] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:34:58,230] {logging_mixin.py:115} INFO - [2022-07-04 18:34:58,230] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:58,242] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:34:58,258] {logging_mixin.py:115} INFO - [2022-07-04 18:34:58,258] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:34:58,275] {logging_mixin.py:115} INFO - [2022-07-04 18:34:58,275] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:34:58,284] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.067 seconds
[2022-07-04 18:35:24,421] {processor.py:153} INFO - Started process (PID=9319) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:24,432] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:35:24,433] {logging_mixin.py:115} INFO - [2022-07-04 18:35:24,432] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:24,434] {logging_mixin.py:115} INFO - [2022-07-04 18:35:24,433] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 33
    name = get_name()
       ^
IndentationError: expected an indented block
[2022-07-04 18:35:24,434] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:24,449] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.029 seconds
[2022-07-04 18:35:45,521] {processor.py:153} INFO - Started process (PID=9352) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:45,521] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:35:45,522] {logging_mixin.py:115} INFO - [2022-07-04 18:35:45,521] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:45,523] {logging_mixin.py:115} INFO - [2022-07-04 18:35:45,522] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 34
    name = get_name()
       ^
IndentationError: expected an indented block
[2022-07-04 18:35:45,523] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:45,538] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.019 seconds
[2022-07-04 18:35:50,555] {processor.py:153} INFO - Started process (PID=9357) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:50,566] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:35:50,567] {logging_mixin.py:115} INFO - [2022-07-04 18:35:50,567] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:50,570] {logging_mixin.py:115} INFO - [2022-07-04 18:35:50,569] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 34
    name = get_name()
       ^
IndentationError: expected an indented block
[2022-07-04 18:35:50,570] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:50,601] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.053 seconds
[2022-07-04 18:35:54,570] {processor.py:153} INFO - Started process (PID=9369) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:54,578] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:35:54,579] {logging_mixin.py:115} INFO - [2022-07-04 18:35:54,579] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:54,580] {logging_mixin.py:115} INFO - [2022-07-04 18:35:54,579] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 34
    name = get_name()
       ^
IndentationError: expected an indented block
[2022-07-04 18:35:54,580] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:35:54,595] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.027 seconds
[2022-07-04 18:36:17,735] {processor.py:153} INFO - Started process (PID=9404) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:17,735] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:36:17,735] {logging_mixin.py:115} INFO - [2022-07-04 18:36:17,735] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:17,737] {logging_mixin.py:115} INFO - [2022-07-04 18:36:17,736] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 34
    name = get_name()
       ^
IndentationError: expected an indented block
[2022-07-04 18:36:17,737] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:17,753] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.020 seconds
[2022-07-04 18:36:47,875] {processor.py:153} INFO - Started process (PID=9437) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:47,876] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:36:47,876] {logging_mixin.py:115} INFO - [2022-07-04 18:36:47,876] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:47,895] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:47,938] {logging_mixin.py:115} INFO - [2022-07-04 18:36:47,938] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:36:47,950] {logging_mixin.py:115} INFO - [2022-07-04 18:36:47,950] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:36:47,964] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.091 seconds
[2022-07-04 18:36:50,930] {processor.py:153} INFO - Started process (PID=9451) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:50,931] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:36:50,931] {logging_mixin.py:115} INFO - [2022-07-04 18:36:50,931] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:50,943] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:50,951] {logging_mixin.py:115} INFO - [2022-07-04 18:36:50,951] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:36:50,967] {logging_mixin.py:115} INFO - [2022-07-04 18:36:50,967] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:36:50,976] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.048 seconds
[2022-07-04 18:36:53,003] {processor.py:153} INFO - Started process (PID=9456) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:53,015] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:36:53,016] {logging_mixin.py:115} INFO - [2022-07-04 18:36:53,016] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:53,053] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:53,062] {logging_mixin.py:115} INFO - [2022-07-04 18:36:53,062] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:36:53,078] {logging_mixin.py:115} INFO - [2022-07-04 18:36:53,077] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:36:53,088] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.093 seconds
[2022-07-04 18:36:55,000] {processor.py:153} INFO - Started process (PID=9461) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:55,009] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:36:55,009] {logging_mixin.py:115} INFO - [2022-07-04 18:36:55,009] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:55,022] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:36:55,030] {logging_mixin.py:115} INFO - [2022-07-04 18:36:55,030] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:36:55,047] {logging_mixin.py:115} INFO - [2022-07-04 18:36:55,047] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:36:55,056] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.057 seconds
[2022-07-04 18:37:07,112] {processor.py:153} INFO - Started process (PID=9480) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:07,114] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:37:07,115] {logging_mixin.py:115} INFO - [2022-07-04 18:37:07,115] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:07,147] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:07,156] {logging_mixin.py:115} INFO - [2022-07-04 18:37:07,156] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:37:07,173] {logging_mixin.py:115} INFO - [2022-07-04 18:37:07,173] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:37:07,185] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.080 seconds
[2022-07-04 18:37:24,232] {processor.py:153} INFO - Started process (PID=9508) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:24,243] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:37:24,243] {logging_mixin.py:115} INFO - [2022-07-04 18:37:24,243] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:24,258] {logging_mixin.py:115} INFO - [2022-07-04 18:37:24,257] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 43, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 41, in hello_world_etl
    get_multiple_name()
NameError: name 'get_multiple_name' is not defined
[2022-07-04 18:37:24,258] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:24,271] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.041 seconds
[2022-07-04 18:37:28,271] {processor.py:153} INFO - Started process (PID=9513) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:28,271] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:37:28,272] {logging_mixin.py:115} INFO - [2022-07-04 18:37:28,271] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:28,287] {logging_mixin.py:115} INFO - [2022-07-04 18:37:28,286] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 44, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 42, in hello_world_etl
    get_multiple_name()
NameError: name 'get_multiple_name' is not defined
[2022-07-04 18:37:28,287] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:28,300] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.032 seconds
[2022-07-04 18:37:41,349] {processor.py:153} INFO - Started process (PID=9537) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:41,360] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:37:41,361] {logging_mixin.py:115} INFO - [2022-07-04 18:37:41,361] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:41,406] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:37:41,452] {logging_mixin.py:115} INFO - [2022-07-04 18:37:41,452] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:37:41,467] {logging_mixin.py:115} INFO - [2022-07-04 18:37:41,467] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:37:41,493] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.148 seconds
[2022-07-04 18:38:11,530] {processor.py:153} INFO - Started process (PID=9579) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:11,541] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:38:11,541] {logging_mixin.py:115} INFO - [2022-07-04 18:38:11,541] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:11,554] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:11,605] {logging_mixin.py:115} INFO - [2022-07-04 18:38:11,605] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:38:11,623] {logging_mixin.py:115} INFO - [2022-07-04 18:38:11,623] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:38:11,635] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.108 seconds
[2022-07-04 18:38:13,553] {processor.py:153} INFO - Started process (PID=9584) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:13,553] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:38:13,554] {logging_mixin.py:115} INFO - [2022-07-04 18:38:13,554] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:13,569] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:13,576] {logging_mixin.py:115} INFO - [2022-07-04 18:38:13,576] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:38:13,591] {logging_mixin.py:115} INFO - [2022-07-04 18:38:13,591] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:38:13,604] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.053 seconds
[2022-07-04 18:38:28,595] {processor.py:153} INFO - Started process (PID=9605) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:28,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:38:28,603] {logging_mixin.py:115} INFO - [2022-07-04 18:38:28,603] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:28,617] {logging_mixin.py:115} INFO - [2022-07-04 18:38:28,615] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 48, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 46, in hello_world_etl
    get_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2022-07-04 18:38:28,617] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:28,629] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.037 seconds
[2022-07-04 18:38:36,656] {processor.py:153} INFO - Started process (PID=9617) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:36,666] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:38:36,667] {logging_mixin.py:115} INFO - [2022-07-04 18:38:36,667] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:36,712] {logging_mixin.py:115} INFO - [2022-07-04 18:38:36,710] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 49, in hello_world_etl
    get_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2022-07-04 18:38:36,712] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:36,729] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.074 seconds
[2022-07-04 18:38:54,802] {processor.py:153} INFO - Started process (PID=9645) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:54,803] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:38:54,803] {logging_mixin.py:115} INFO - [2022-07-04 18:38:54,803] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:54,823] {logging_mixin.py:115} INFO - [2022-07-04 18:38:54,822] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 49, in hello_world_etl
    get_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2022-07-04 18:38:54,824] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:38:54,838] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.040 seconds
[2022-07-04 18:39:10,952] {processor.py:153} INFO - Started process (PID=9669) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:10,955] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:39:10,957] {logging_mixin.py:115} INFO - [2022-07-04 18:39:10,956] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:10,992] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:11,034] {logging_mixin.py:115} INFO - [2022-07-04 18:39:11,034] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:39:11,047] {logging_mixin.py:115} INFO - [2022-07-04 18:39:11,047] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:39:11,060] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.115 seconds
[2022-07-04 18:39:35,044] {processor.py:153} INFO - Started process (PID=9704) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:35,044] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:39:35,044] {logging_mixin.py:115} INFO - [2022-07-04 18:39:35,044] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:35,059] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:35,066] {logging_mixin.py:115} INFO - [2022-07-04 18:39:35,066] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:39:35,081] {logging_mixin.py:115} INFO - [2022-07-04 18:39:35,081] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:39:35,090] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.048 seconds
[2022-07-04 18:39:48,143] {processor.py:153} INFO - Started process (PID=9725) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:48,152] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:39:48,153] {logging_mixin.py:115} INFO - [2022-07-04 18:39:48,153] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:48,171] {logging_mixin.py:115} INFO - [2022-07-04 18:39:48,170] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 48, in hello_world_etl
    name_dict = set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:39:48,171] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:48,183] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.042 seconds
[2022-07-04 18:39:58,171] {processor.py:153} INFO - Started process (PID=9738) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:58,171] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:39:58,172] {logging_mixin.py:115} INFO - [2022-07-04 18:39:58,172] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:58,189] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:39:58,236] {logging_mixin.py:115} INFO - [2022-07-04 18:39:58,236] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:39:58,251] {logging_mixin.py:115} INFO - [2022-07-04 18:39:58,251] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:39:58,266] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.097 seconds
[2022-07-04 18:40:17,351] {processor.py:153} INFO - Started process (PID=9762) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:17,363] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:40:17,364] {logging_mixin.py:115} INFO - [2022-07-04 18:40:17,364] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:17,403] {logging_mixin.py:115} INFO - [2022-07-04 18:40:17,402] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 48, in hello_world_etl
    name_dict = set_multiple_name(ggreet_result)
NameError: name 'ggreet_result' is not defined
[2022-07-04 18:40:17,403] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:17,416] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.074 seconds
[2022-07-04 18:40:19,402] {processor.py:153} INFO - Started process (PID=9776) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:19,410] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:40:19,411] {logging_mixin.py:115} INFO - [2022-07-04 18:40:19,411] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:19,429] {processor.py:651} INFO - DAG(s) dict_keys(['dag_with_taskflow_api']) retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:19,438] {logging_mixin.py:115} INFO - [2022-07-04 18:40:19,438] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-04 18:40:19,460] {logging_mixin.py:115} INFO - [2022-07-04 18:40:19,460] {dag.py:2931} INFO - Setting next_dagrun for dag_with_taskflow_api to 2022-07-04T00:00:00+00:00, run_after=2022-07-05T00:00:00+00:00
[2022-07-04 18:40:19,476] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.076 seconds
[2022-07-04 18:40:43,564] {processor.py:153} INFO - Started process (PID=9809) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:43,564] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:40:43,565] {logging_mixin.py:115} INFO - [2022-07-04 18:40:43,565] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:43,593] {logging_mixin.py:115} INFO - [2022-07-04 18:40:43,591] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:40:43,593] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:40:43,606] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.048 seconds
[2022-07-04 18:41:13,695] {processor.py:153} INFO - Started process (PID=9842) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:13,707] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:41:13,708] {logging_mixin.py:115} INFO - [2022-07-04 18:41:13,708] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:13,724] {logging_mixin.py:115} INFO - [2022-07-04 18:41:13,723] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:41:13,724] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:13,737] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.043 seconds
[2022-07-04 18:41:43,902] {processor.py:153} INFO - Started process (PID=9884) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:43,911] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:41:43,911] {logging_mixin.py:115} INFO - [2022-07-04 18:41:43,911] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:43,924] {logging_mixin.py:115} INFO - [2022-07-04 18:41:43,922] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:41:43,924] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:41:43,938] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.038 seconds
[2022-07-04 18:42:10,071] {processor.py:153} INFO - Started process (PID=9926) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:10,082] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:42:10,082] {logging_mixin.py:115} INFO - [2022-07-04 18:42:10,082] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:10,094] {logging_mixin.py:115} INFO - [2022-07-04 18:42:10,093] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:42:10,094] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:10,109] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.040 seconds
[2022-07-04 18:42:40,256] {processor.py:153} INFO - Started process (PID=9959) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:40,264] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:42:40,264] {logging_mixin.py:115} INFO - [2022-07-04 18:42:40,264] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:40,276] {logging_mixin.py:115} INFO - [2022-07-04 18:42:40,275] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:42:40,276] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:40,290] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.043 seconds
[2022-07-04 18:42:45,291] {processor.py:153} INFO - Started process (PID=9973) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:45,291] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:42:45,291] {logging_mixin.py:115} INFO - [2022-07-04 18:42:45,291] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:45,304] {logging_mixin.py:115} INFO - [2022-07-04 18:42:45,302] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:42:45,304] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:45,318] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.029 seconds
[2022-07-04 18:42:54,329] {processor.py:153} INFO - Started process (PID=9987) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:54,330] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:42:54,331] {logging_mixin.py:115} INFO - [2022-07-04 18:42:54,330] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:54,355] {logging_mixin.py:115} INFO - [2022-07-04 18:42:54,353] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:42:54,356] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:42:54,384] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.058 seconds
[2022-07-04 18:43:24,458] {processor.py:153} INFO - Started process (PID=10020) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:24,468] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:43:24,469] {logging_mixin.py:115} INFO - [2022-07-04 18:43:24,469] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:24,481] {logging_mixin.py:115} INFO - [2022-07-04 18:43:24,479] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:43:24,482] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:24,498] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.042 seconds
[2022-07-04 18:43:54,603] {processor.py:153} INFO - Started process (PID=10062) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:54,609] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:43:54,609] {logging_mixin.py:115} INFO - [2022-07-04 18:43:54,609] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:54,623] {logging_mixin.py:115} INFO - [2022-07-04 18:43:54,622] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:43:54,623] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:43:54,636] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.037 seconds
[2022-07-04 18:44:24,776] {processor.py:153} INFO - Started process (PID=10104) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:24,787] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:44:24,789] {logging_mixin.py:115} INFO - [2022-07-04 18:44:24,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:24,826] {logging_mixin.py:115} INFO - [2022-07-04 18:44:24,824] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:44:24,827] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:24,842] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.074 seconds
[2022-07-04 18:44:54,985] {processor.py:153} INFO - Started process (PID=10137) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:54,986] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:44:54,987] {logging_mixin.py:115} INFO - [2022-07-04 18:44:54,987] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:55,021] {logging_mixin.py:115} INFO - [2022-07-04 18:44:55,019] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:44:55,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:44:55,036] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.059 seconds
[2022-07-04 18:45:25,159] {processor.py:153} INFO - Started process (PID=10179) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:25,170] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:45:25,172] {logging_mixin.py:115} INFO - [2022-07-04 18:45:25,172] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:25,210] {logging_mixin.py:115} INFO - [2022-07-04 18:45:25,208] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:45:25,210] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:25,225] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.074 seconds
[2022-07-04 18:45:55,345] {processor.py:153} INFO - Started process (PID=10221) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:55,355] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:45:55,356] {logging_mixin.py:115} INFO - [2022-07-04 18:45:55,356] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:55,369] {logging_mixin.py:115} INFO - [2022-07-04 18:45:55,368] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:45:55,369] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:45:55,382] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.038 seconds
[2022-07-04 18:46:25,563] {processor.py:153} INFO - Started process (PID=10263) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:25,575] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:46:25,576] {logging_mixin.py:115} INFO - [2022-07-04 18:46:25,575] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:25,605] {logging_mixin.py:115} INFO - [2022-07-04 18:46:25,603] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:46:25,606] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:25,621] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.063 seconds
[2022-07-04 18:46:55,740] {processor.py:153} INFO - Started process (PID=10296) to work on /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:55,742] {processor.py:641} INFO - Processing file /opt/airflow/dags/my_taskflow_api_dag.py for tasks to queue
[2022-07-04 18:46:55,743] {logging_mixin.py:115} INFO - [2022-07-04 18:46:55,743] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:55,773] {logging_mixin.py:115} INFO - [2022-07-04 18:46:55,771] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/my_taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 51, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2979, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/my_taskflow_api_dag.py", line 47, in hello_world_etl
    greet(name=name, age=age) >> set_multiple_name()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 264, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 55, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 172, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'greet'
[2022-07-04 18:46:55,773] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/my_taskflow_api_dag.py
[2022-07-04 18:46:55,788] {processor.py:161} INFO - Processing /opt/airflow/dags/my_taskflow_api_dag.py took 0.056 seconds
